/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sischat.client;

import sischat.member.ChatMember;
import sischat.msg.ChatMessage;
import sischat.p2p.P2PClient;
import sischat.p2p.P2PListener;

/**
 *
 * @author Visat
 */
public class ChatP2P extends javax.swing.JFrame implements P2PListener {

    P2PClient client;

    /**
     * Creates new form ChatP2P
     * @param client
     */
    public ChatP2P(P2PClient client) {
        this.client = client;
        this.client.addListener(this);
        initComponents();
        this.setTitle(client.getReceiver().getName());
        this.textMessage.requestFocus();
    }

    public void onDisconnected() {
        textMessageList.append(client.getReceiver().getName() + " is disconnected\n");
        textMessage.setEnabled(false);
        buttonSend.setEnabled(false);
    }

    @Override
    public void onConnected(ChatMember member) {

    }

    @Override
    public void onDisconnected(ChatMember member) {
        onDisconnected();
    }

    @Override
    public void onMessage(ChatMessage message) {
        this.setVisible(true);
        textMessage.setEnabled(true);
        buttonSend.setEnabled(true);
        textMessageList.append(message.getSender() + ": " + message.getContent() + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textMessage = new javax.swing.JTextField();
        buttonSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMessageList = new javax.swing.JTextArea();

        textMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMessageActionPerformed(evt);
            }
        });

        buttonSend.setText("Send");
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });

        textMessageList.setEditable(false);
        textMessageList.setColumns(20);
        textMessageList.setRows(5);
        jScrollPane1.setViewportView(textMessageList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSend, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSend))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        textMessage.setText(textMessage.getText().trim());
        if (textMessage.getText().length() > 0) {
            if (client.doMessage(textMessage.getText())) {
                textMessageList.append("You: " + textMessage.getText() + "\n");
                textMessage.setText("");
            }
            else {
                onDisconnected();
            }
            textMessage.setText("");
            textMessage.requestFocus();
        }
    }//GEN-LAST:event_buttonSendActionPerformed

    private void textMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMessageActionPerformed
        buttonSend.doClick();
    }//GEN-LAST:event_textMessageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textMessage;
    private javax.swing.JTextArea textMessageList;
    // End of variables declaration//GEN-END:variables


}
